const defaultParts=["Fender","Hood","Door Panel","Quarter Panel","Rocker Panel","Bumper","Radiator Support"].map(name=>({id:crypto.randomUUID(),name,image:"",youtube:"",notes:""}));
const STORAGE_KEY="panel_beater_study_parts_v1";
let parts=loadParts(),selectedId=parts[0]?.id||null;
const $=id=>document.getElementById(id);
const partsList=$("partsList"),searchInput=$("searchInput"),addBtn=$("addBtn"),emptyState=$("emptyState"),detailCard=$("detailCard"),detailName=$("detailName"),mainPartName=$("mainPartName"),mainImageUrl=$("mainImageUrl"),imagesBtn=$("imagesBtn"),mainYoutubeUrl=$("mainYoutubeUrl"),videoPreview=$("videoPreview"),videoThumb=$("videoThumb"),noPreview=$("noPreview"),watchBtn=$("watchBtn"),notesArea=$("notesArea"),saveChangesBtn=$("saveChangesBtn"),deletePartBtn=$("deletePartBtn"),statParts=$("statParts"),statVideos=$("statVideos"),statImages=$("statImages"),statNotes=$("statNotes");
function loadParts(){const s=localStorage.getItem(STORAGE_KEY);if(!s){localStorage.setItem(STORAGE_KEY,JSON.stringify(defaultParts));return defaultParts}try{return JSON.parse(s)}catch{return defaultParts}}
function saveParts(){localStorage.setItem(STORAGE_KEY,JSON.stringify(parts))}
function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function url(v){v=v.trim();if(!v)return"";return /^https?:\/\//i.test(v)?v:"https://"+v}
function youtubeId(v){try{const u=new URL(url(v));if(u.hostname.includes("youtu.be"))return u.pathname.split("/")[1]?.split("?")[0]||"";if(u.hostname.includes("youtube.com")){if(u.pathname==="/watch")return u.searchParams.get("v")||"";const m=u.pathname.match(/\/(?:shorts|embed|live)\/([^/?]+)/);return m?m[1]:""}}catch{}return""}
function setLink(el,v,on,off){if(v){el.href=url(v);el.textContent=on;el.classList.remove("disabled")}else{el.removeAttribute("href");el.textContent=off;el.classList.add("disabled")}}
function updateStats(){statParts.textContent=parts.length;statVideos.textContent=parts.filter(p=>p.youtube).length;statImages.textContent=parts.filter(p=>p.image).length;statNotes.textContent=parts.filter(p=>p.notes&&p.notes.trim()).length}
function renderParts(filter=""){const q=filter.trim().toLowerCase();partsList.innerHTML="";parts.filter(p=>p.name.toLowerCase().includes(q)).forEach(p=>{const row=document.createElement("button");row.type="button";row.className="part-item"+(p.id===selectedId?" active":"");row.innerHTML=`<div class="part-icon">◫</div><div class="part-text"><div class="part-name">${esc(p.name)}</div><div class="part-sub">${p.image?"Images ready":"No image link"} · ${p.youtube?"Video ready":"No video"}</div></div><div class="chev">›</div>`;row.onclick=()=>{selectedId=p.id;renderParts(searchInput.value);renderDetail();if(innerWidth<=820)document.querySelector(".main-area").scrollIntoView({behavior:"smooth"})};partsList.appendChild(row)});updateStats()}
function renderDetail(){const p=parts.find(x=>x.id===selectedId);if(!p){emptyState.classList.remove("hidden");detailCard.classList.add("hidden");return}emptyState.classList.add("hidden");detailCard.classList.remove("hidden");detailName.textContent=p.name;mainPartName.value=p.name;mainImageUrl.value=p.image||"";mainYoutubeUrl.value=p.youtube||"";notesArea.value=p.notes||"";setLink(imagesBtn,p.image,"▧ VIEW IMAGES","NO IMAGE LINK YET");setLink(watchBtn,p.youtube,"▶ WATCH VIDEO","NO VIDEO LINK YET");renderVideoPreview(p.youtube)}
function renderVideoPreview(v){const id=youtubeId(v||"");if(!id){videoPreview.classList.add("hidden");noPreview.classList.remove("hidden");videoThumb.removeAttribute("src");return}videoThumb.src=`https://img.youtube.com/vi/${id}/hqdefault.jpg`;videoPreview.classList.remove("hidden");noPreview.classList.add("hidden");videoPreview.onclick=()=>window.open(url(v),"_blank","noopener,noreferrer")}
function saveCurrent(){const p=parts.find(x=>x.id===selectedId);if(!p)return;p.name=mainPartName.value.trim()||p.name;p.image=url(mainImageUrl.value);p.youtube=url(mainYoutubeUrl.value);p.notes=notesArea.value;saveParts();renderParts(searchInput.value);renderDetail();saveChangesBtn.textContent="SAVED ✓";setTimeout(()=>saveChangesBtn.textContent="💾 SAVE CHANGES",1200)}
saveChangesBtn.onclick=saveCurrent;
addBtn.onclick=()=>{const p={id:crypto.randomUUID(),name:"New Part",image:"",youtube:"",notes:""};parts.push(p);selectedId=p.id;saveParts();renderParts(searchInput.value);renderDetail();mainPartName.focus();mainPartName.select()};
deletePartBtn.onclick=()=>{const p=parts.find(x=>x.id===selectedId);if(!p)return;if(!confirm(`Delete ${p.name}?`))return;parts=parts.filter(x=>x.id!==selectedId);selectedId=parts[0]?.id||null;saveParts();renderParts(searchInput.value);renderDetail()};
searchInput.oninput=e=>renderParts(e.target.value);
mainImageUrl.oninput=()=>setLink(imagesBtn,mainImageUrl.value,"▧ VIEW IMAGES","NO IMAGE LINK YET");
mainYoutubeUrl.oninput=()=>{setLink(watchBtn,mainYoutubeUrl.value,"▶ WATCH VIDEO","NO VIDEO LINK YET");renderVideoPreview(mainYoutubeUrl.value)};
renderParts();renderDetail();